//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vvedenie_dolzhnosti
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    //  *** Start programmer edit section *** (Должность CustomAttributes)

    //  *** End programmer edit section *** (Должность CustomAttributes)
    [PublishName("Должность")]
    [ClassStorage("БД")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ДолжностьE", new string[0])]
    [View("ДолжностьL", new string[0])]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Должность CustomMembers)

        //  *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Vvedenie_dolzhnosti.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Vvedenie_dolzhnosti.Должность));
                }
            }
        }
    }
}
